
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { supabaseAuth } from './auth-client';
import { supabaseDb } from './db-client';
import { supabaseStorage } from './storage-client';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './base-client';

// DEPRECATION WARNING:
// This monolithic client is deprecated. For optimized imports, use the specialized clients:
// - Authentication: import { supabaseAuth } from '@/integrations/supabase/auth-client'
// - Database: import { supabaseDb } from '@/integrations/supabase/db-client'
// - Storage: import { supabaseStorage } from '@/integrations/supabase/storage-client'

// Legacy client for backward compatibility
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Re-export specialized clients for direct access
export { supabaseAuth, supabaseDb, supabaseStorage };
